kind: Service
apiVersion: v1
metadata:
  name: mysql-headless
  namespace: expense
  labels:
    project: expense
    tier: mysql
    folder: helm
spec:
  clusterIP: None
  selector:
    project: expense
    tier: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306

---

kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: expense
  labels:
    project: expense
    tier: mysql
    folder: helm
spec:
  selector:
    project: expense
    tier: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
